services:
  database:
    image: "postgres:16.0-alpine3.18"
    env_file:
      - ../.env.development
    ports:
      - "5432:5432"

  postgres-app:
    image: postgres:latest
    environment:
      - POSTGRES_CA=${POSTGRES_CA}
